### ISSUE TITLE
camera examples do not work on the demo website

### ISSUE THREAD

**Issue by DanielRuf** [eduardolundgren/tracking.js#322] opened 2018-06-17 21:48 UTC

**Comment by cyzeng-Luca** [comment] 2018-06-27 06:06
Duplicate of #328

**Comment by DanielRuf** [comment] 2018-06-27 06:33
Mine is older, see the issue number ;-)

**Comment by stephenguerin** [comment] 2018-07-01 21:29
error in console:
`tracking-min.js:8 [Deprecation] URL.createObjectURL with media streams is deprecated and will be removed in M68, around July 2018. Please use HTMLMediaElement.srcObject instead. See https://www.chromestatus.com/features/5618491470118912 for more details.`

**Comment by mskogly** [comment] 2018-08-28 14:07
Is there any browser that can run the fast camera example? https://trackingjs.com/examples/fast_camera.html 
Any way to fix it?

**Comment by bid** [comment] 2018-08-28 20:44
"Is there any browser that can run the fast camera example?" Most likely not, given that the webcam APIs tracking.js uses have been deprecated for 5 YEARS now...

**Comment by mskogly** [comment] 2018-08-29 07:02
I went through some old code of mine and actually found a fast camera example that works. No idea why this one plays and non of the other, or the original example file. Is does give a deprecation warning in Chrome console, but it plays fine, at least on my setup. At least until september 2018 :)
https://pappmaskin.no/opensource/trackingjs/examples/fast_camera-onload-draw.html

"[Deprecation] URL.createObjectURL with media streams is deprecated and will be removed in M69, around September 2018. Please use HTMLMediaElement.srcObject instead. See https://www.chromestatus.com/features/5618491470118912 for more details."

**Comment by ayzakh** [comment] 2019-05-22 09:58
hey, what i can do?

**Comment by ayzakh** [comment] 2019-05-22 10:45
I found a cdn issue
![Screenshot 2019-05-22 at 19 42 11](https://user-images.githubusercontent.com/9413058/58168780-0de72180-7cca-11e9-9360-5645f1ced224.png)

**Comment by ayzakh** [comment] 2019-05-22 10:45
1.1.3 version works fine

**Comment by DanielRuf** [comment] 2019-05-22 10:53
This is not a CDN issue per se.
See http://unpkg.com/tracking which redirects to https://unpkg.com/tracking@1.1.3/build/tracking.js

Also see https://unpkg.com/tracking@1.1.3/build/tracking-min.js

There was only the wrong code published and pushed to npmjs and others.

**Comment by ayzakh** [comment] 2019-05-22 12:20
Yes, it saved in all cdn's

**Comment by DanielRuf** [comment] 2019-05-22 12:22
> Yes, it saved in all cdns

Sure because these are mostly mirrors of npmjs ;-)

**Closed** 2020-09-13 20:36 UTC
